version: '3.8'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - JAVA_TIMEZONE=UTC
    restart: unless-stopped
    volumes:
      - metabase_data:/metabase-data

volumes:
  metabase_data:
